USE CUST_DB
ALTER DATABASE CUST_DB

ADD FILE (NAME = Cust_DB1, FILENAME = 'C:\ProgramFiles\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Cust_DB1.ndf')

TO FILEGROUP FG_ReadOnly

ALTER DATABASE CUST_DB

MODIFY FILEGROUP FG_ReadOnly DEFAULT

